export const product = [
  {
    id: 1,
    img: "./images/11.jpg",
    name: "iPhone 11",
    price: "$450",
    category: "iphone",
  },
  {
    id: 2,
    img: "./images/11 pro.jpg",
    name: "iPhone 11 pro",
    price: "$550",
    category: "iphone",
  },
  {
    id: 3,
    img: "./images/12.jpg",
    name: "iPhone 12",
    price: "$650",
    category: "iphone",
  },
  {
    id: 4,
    img: "./images/12 pro.jpg",
    name: "iPhone 12 pro",
    price: "$700",
    category: "iphone",
  },
  {
    id: 5,
    img: "./images/13 pro max.jpg",
    name: "iPhone 13 pro and pro max",
    price: "$750",
    category: "iphone",
  },
  {
    id: 6,
    img: "./images/14.jpg",
    name: "iPhone 14",
    price: "$800",
    category: "iphone",
  },
  {
    id: 7,
    img: "./images/14 pro max.jpg",
    name: "iPhone 14 pro and pro max",
    price: "$950",
    category: "iphone",
  },
  {
    id: 8,
    img: "./images/15.jpg",
    name: "iPhone 15",
    price: "$1000",
    category: "iphone",
  },
  {
    id: 9,
    img: "./images/ipad.jpg",
    name: "ipad",
    price: "$558",
    category: "iphone",
  },
  {
    id: 10,
    img: "./images/ipad air 4.jpg",
    name: "ipad Air 4",
    price: "$658",
    category: "ipad",
  },
  {
    id: 11,
    img: "./images/ipad minii.jpeg",
    name: "ipad Mini",
    price: "$358",
    category: "ipad",
  },
  {
    id: 12,
    img: "./images/ipad pro.jpg",
    name: "ipad Pro",
    price: "$758",
    category: "ipad",
  },
  {
    id: 13,
    img: "./images/macbook-air-2017.jpeg",
    name: "macbook air 2017",
    price: "$1900",
    category: "macbook",
  },
  {
    id: 14,
    img: "./images/macbook-air-midnight-select-20220606.jpeg",
    name: "macbook Air Midnight",
    price: "$1800",
    category: "macbook",
  },
  {
    id: 15,
    img: "./images/macbookair_2021.png",
    name: "macbook air 2021",
    price: "$2100",
    category: "macbook",
  },
  {
    id: 16,
    img: "./images/mbp16-spaceblack-select-202310.jpeg",
    name: "macbook Pro 16",
    price: "$2900",
    category: "macbook",
  },
  {
    id: 17,
    img: "./images/hermes.jpg",
    name: "watch Hermes",
    price: "$700",
    category: "watch",
  },
  {
    id: 18,
    img: "./images/nike.jpg",
    name: "watch Nike",
    price: "$750",
    category: "watch",
  },
  {
    id: 19,
    img: "./images/ultra 2.jpg",
    name: "watch Ultra 2",
    price: "$780",
    category: "watch",
  },
  {
    id: 20,
    img: "./images/watsh series 9.jpg",
    name: "watch Series 9",
    price: "$790",
    category: "watch",
  },
  {
    id: 21,
    img: "./images/se.jpg",
    name: "watch SE",
    price: "$890",
    category: "watch",
  },
];
